### PR TITLE
Don't hardcode a provider for the postgresql server package

### PR DESCRIPTION
**Pull request by mattr-**
Let Puppet determine the proper provider to use.

### CODE REVIEW

**Comment by akumria** [comment]
Hi Matt,

Thanks for the diff, but I'm confused how this patch helps you.

What problem are you having that this solves?

**Comment by mattr-** [comment]
It's part of another set of changes I have upcoming that allow this module to be used with non-Debian distorts.

**Comment by mattr-** [comment]
It doesn't solve a particular problem that I'm having. I did it in an
attempt to remove the platform specific stuff from the module so that I
could use it on a RedHat or CentOS system.

I have more changes in the works for that as well. Are you interested in
supporting this module on multiple operating systems?

On Sep 2, 2012, at 6:22 PM, Anand Kumria notifications@github.com wrote:

Hi Matt,

Thanks for the diff, but I'm confused how this patch helps you.

What problem are you having that this solves?

—
Reply to this email directly or view it on
GitHubhttps://github.com/akumria/puppet-postgresql/pull/6#issuecomment-8227227.

**Comment by akumria** [comment]
Hi Matt,

Yes I am interested in having the module work on multiple platforms, but without seeing the rest of the changes you have pending it is hard to see how things all fit together.

Does this need to be merged _before_ you can send a pull request for your additional changes?

Thanks,
Anand

**Comment by akumria** [comment]
It has been 7 months since I've heard anything, or seen any further patches.

Closing.

**Pull request closed without merging**
